name: Deploy n8n

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Push to Docker Hub (اختياري)
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t your-docker-username/n8n:latest .
          docker push your-docker-username/n8n:latest
